// Command current-form-source renders the current Edge-first versionless Form
// Family and the Interface and Binding candidate sets it requires. The
// publisher remains provider-neutral: generated bytes are data-only candidates
// and do not imply a Host implementation or release.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"github.com/tako0614/takoform-forms/internal/edgeformcatalog"
)

type sourceDocument struct {
	PackageAPIVersion        string           `json:"packageApiVersion"`
	FamilyIndexFormat        string           `json:"familyIndexFormat"`
	FormMaturity             string           `json:"formMaturity"`
	PublicationStatus        string           `json:"publicationStatus"`
	InterfaceAuthoringSource string           `json:"interfaceAuthoringSource"`
	BindingAuthoringSource   string           `json:"bindingAuthoringSource"`
	Families                 []sourceFamily   `json:"families"`
	Interfaces               []sourceContract `json:"interfaces"`
	Bindings                 []sourceContract `json:"bindings"`
}

type sourceFamily struct {
	Group           string          `json:"group"`
	AuthoringSource string          `json:"authoringSource"`
	AuthoringPolicy string          `json:"authoringPolicy"`
	Forms           json.RawMessage `json:"forms"`
}

type sourceContract struct {
	Name           string `json:"name"`
	Version        string `json:"version"`
	DefinitionJSON string `json:"definitionJson"`
	SchemaDigest   string `json:"schemaDigest"`
}

func main() {
	if len(os.Args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: current-form-source")
		os.Exit(2)
	}
	document, err := renderSource()
	if err != nil {
		fail(err)
	}
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(document); err != nil {
		fail(err)
	}
}

func renderSource() (sourceDocument, error) {
	document := sourceDocument{
		PackageAPIVersion:        "packages.forms.takoform.com/v1alpha5",
		FamilyIndexFormat:        "takoform.current-family-index@v1",
		FormMaturity:             "experimental",
		PublicationStatus:        "unpublished",
		InterfaceAuthoringSource: "cmd/current-form-source",
		BindingAuthoringSource:   "cmd/current-form-source",
	}
	appendFamily := func(group, authoringSource string, forms any) error {
		raw, err := json.Marshal(forms)
		if err != nil {
			return fmt.Errorf("marshal %s source Forms: %w", group, err)
		}
		document.Families = append(document.Families, sourceFamily{
			Group:           group,
			AuthoringSource: authoringSource,
			AuthoringPolicy: "service-shape-preserving-contract",
			Forms:           raw,
		})
		return nil
	}
	appendContracts := func(destination *[]sourceContract, contracts any) error {
		raw, err := json.Marshal(contracts)
		if err != nil {
			return err
		}
		var decoded []sourceContract
		if err := json.Unmarshal(raw, &decoded); err != nil {
			return err
		}
		*destination = append(*destination, decoded...)
		return nil
	}

	// Edge is the current publisher composition. Other family catalogs were
	// unpublished candidates and are intentionally deferred; they are not
	// represented in this source document or in generated candidate output.
	edgeForms, err := edgeformcatalog.RenderForms()
	if err != nil {
		return sourceDocument{}, fmt.Errorf("render Edge Forms: %w", err)
	}
	if err := appendFamily(edgeformcatalog.Family.APIVersion(), "internal/edgeformcatalog", edgeForms); err != nil {
		return sourceDocument{}, err
	}
	edgeInterfaces, err := edgeformcatalog.RenderInterfaces()
	if err != nil {
		return sourceDocument{}, fmt.Errorf("render Edge Interfaces: %w", err)
	}
	if err := appendContracts(&document.Interfaces, edgeInterfaces); err != nil {
		return sourceDocument{}, err
	}
	edgeBindings, err := edgeformcatalog.RenderBindings()
	if err != nil {
		return sourceDocument{}, fmt.Errorf("render Edge Bindings: %w", err)
	}
	if err := appendContracts(&document.Bindings, edgeBindings); err != nil {
		return sourceDocument{}, err
	}
	// Keep the source's single family deterministic even if the implementation
	// later grows another composition stage.
	sort.Slice(document.Families, func(left, right int) bool {
		return document.Families[left].Group < document.Families[right].Group
	})
	for _, contracts := range []*[]sourceContract{&document.Interfaces, &document.Bindings} {
		if err := sortExactContracts(*contracts); err != nil {
			return sourceDocument{}, err
		}
	}
	return document, nil
}

func sortExactContracts(contracts []sourceContract) error {
	sort.Slice(contracts, func(left, right int) bool {
		if contracts[left].Name != contracts[right].Name {
			return contracts[left].Name < contracts[right].Name
		}
		return contracts[left].Version < contracts[right].Version
	})
	for index := 1; index < len(contracts); index++ {
		previous, current := contracts[index-1], contracts[index]
		if previous.Name == current.Name && previous.Version == current.Version {
			return fmt.Errorf("global contract set duplicates exact identity %s@%s", current.Name, current.Version)
		}
	}
	return nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "current-form-source:", err)
	os.Exit(1)
}
